try to workaround error (to make real, will require updating ic-hs)
error: current package believes it's in a workspace when it's not:
current:   /home/runner/work/agent-rs/agent-rs/ic-hs/universal-canister/Cargo.toml
workspace: /home/runner/work/agent-rs/agent-rs/Cargo.toml

this may be fixable by adding `ic-hs/universal-canister` to the `workspace.members` array of the manifest located at: /home/runner/work/agent-rs/agent-rs/Cargo.toml
Alternatively, to keep it out of the workspace, add the package to the `workspace.exclude` array, or add an empty `[workspace]` table to the package's manifest.